pipeline {
    agent {
        docker {
            filename 'test.Dockerfile'
        }
    }

    stages {
        stage('Lint') {
            steps {
                sh 'flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics'
                sh 'flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest --verbose --junit-xml test-reports/results.xml ./modules'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}