pipeline {
    agent none
    stages {
        stage('Lint') {
            agent {
                docker {
                    image 'python:3.9.16-bullseye'
                }
            }
            steps {
                sh 'pip install flake8'
                sh 'if [ -f requirements.txt ]; then pip install -r requirements.txt; fi'
                sh 'flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics'
                sh 'flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}